services:
  migrate:
    build: .
    command: alembic upgrade head
    environment:
      - DATABASE_URL=${DATABASE_URL:?err}
    depends_on:
      db:
        condition: service_healthy
    restart: no
    env_file:
      - .env
  api:
    build: .
    working_dir: /pizza_app  # ← важно!
    container_name: api
    depends_on:
      db:
        condition: service_healthy
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL:?err}
    volumes:
      # 🔥 Пробрасываем локальную папку в контейнер
      - ./:/pizza_app  # Путь внутри контейнера должен совпадать с WORKDIR в Dockerfile
      # Исключаем синхронизацию лишних файлов (опционально, но рекомендуется)
      - /pizza_app/.venv
      - /pizza_app/__pycache__
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
  db:
    image: postgres:15
    container_name: pizzasAppDb
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    ports:
      - "5432:5432"