"""add basket

Revision ID: 383fedc33601
Revises: d8172ffb14a4
Create Date: 2026-07-02 13:49:52.504137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '383fedc33601'
down_revision: Union[str, Sequence[str], None] = 'd8172ffb14a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('busket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pizza_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('pizza_value', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_busket_id'), 'busket', ['id'], unique=False)
    op.create_index(op.f('ix_busket_pizza_id'), 'busket', ['pizza_id'], unique=False)
    op.create_index(op.f('ix_busket_user_id'), 'busket', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_busket_user_id'), table_name='busket')
    op.drop_index(op.f('ix_busket_pizza_id'), table_name='busket')
    op.drop_index(op.f('ix_busket_id'), table_name='busket')
    op.drop_table('busket')
    # ### end Alembic commands ###
