"""add basket

Revision ID: 5d3049b5ef80
Revises: 383fedc33601
Create Date: 2026-07-02 14:19:36.138996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d3049b5ef80'
down_revision: Union[str, Sequence[str], None] = '383fedc33601'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('busket', sa.Column('user_email', sa.String(length=100), nullable=False))
    op.alter_column('busket', 'pizza_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('busket', 'pizza_value',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_busket_user_id'), table_name='busket')
    op.create_index(op.f('ix_busket_user_email'), 'busket', ['user_email'], unique=False)
    op.drop_column('busket', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('busket', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_busket_user_email'), table_name='busket')
    op.create_index(op.f('ix_busket_user_id'), 'busket', ['user_id'], unique=False)
    op.alter_column('busket', 'pizza_value',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('busket', 'pizza_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('busket', 'user_email')
    # ### end Alembic commands ###
