"""fix register tables

Revision ID: 74d47e4957a3
Revises: 2965189d1d0b
Create Date: 2026-05-04 19:29:18.078050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74d47e4957a3'
down_revision: Union[str, Sequence[str], None] = '2965189d1d0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pizzasCatalog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('namePizza', sa.String(length=100), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('ingridients', sa.String(), nullable=False),
    sa.Column('picturePizza', sa.String(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('thicknessDough', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pizzasCatalog_id'), 'pizzasCatalog', ['id'], unique=False)
    op.create_index(op.f('ix_pizzasCatalog_namePizza'), 'pizzasCatalog', ['namePizza'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.drop_index(op.f('ix_Users_email'), table_name='Users')
    op.drop_index(op.f('ix_Users_id'), table_name='Users')
    op.drop_index(op.f('ix_Users_username'), table_name='Users')
    op.drop_table('Users')
    op.drop_index(op.f('ix_PizzasCatalog_id'), table_name='PizzasCatalog')
    op.drop_index(op.f('ix_PizzasCatalog_namePizza'), table_name='PizzasCatalog')
    op.drop_table('PizzasCatalog')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PizzasCatalog',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('namePizza', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('cost', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ingridients', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('picturePizza', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('size', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('thicknessDough', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('PizzasCatalog_pkey'))
    )
    op.create_index(op.f('ix_PizzasCatalog_namePizza'), 'PizzasCatalog', ['namePizza'], unique=False)
    op.create_index(op.f('ix_PizzasCatalog_id'), 'PizzasCatalog', ['id'], unique=False)
    op.create_table('Users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('Users_pkey'))
    )
    op.create_index(op.f('ix_Users_username'), 'Users', ['username'], unique=False)
    op.create_index(op.f('ix_Users_id'), 'Users', ['id'], unique=False)
    op.create_index(op.f('ix_Users_email'), 'Users', ['email'], unique=True)
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_pizzasCatalog_namePizza'), table_name='pizzasCatalog')
    op.drop_index(op.f('ix_pizzasCatalog_id'), table_name='pizzasCatalog')
    op.drop_table('pizzasCatalog')
    # ### end Alembic commands ###
