"""fix nametables

Revision ID: d8172ffb14a4
Revises: 29abecf49b4d
Create Date: 2026-05-28 13:13:52.824606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8172ffb14a4'
down_revision: Union[str, Sequence[str], None] = '29abecf49b4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pizzasCatalog', sa.Column('ingredients', sa.String(), nullable=False))
    op.drop_column('pizzasCatalog', 'ingridients')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pizzasCatalog', sa.Column('ingridients', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('pizzasCatalog', 'ingredients')
    # ### end Alembic commands ###
