"""fix 1

Revision ID: ea26ff22e5ed
Revises: acd14be8571f
Create Date: 2026-07-02 14:39:19.539983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea26ff22e5ed'
down_revision: Union[str, Sequence[str], None] = 'acd14be8571f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('basket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pizza_id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(length=100), nullable=False),
    sa.Column('pizza_value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_basket_id'), 'basket', ['id'], unique=False)
    op.create_index(op.f('ix_basket_pizza_id'), 'basket', ['pizza_id'], unique=False)
    op.create_index(op.f('ix_basket_user_email'), 'basket', ['user_email'], unique=False)
    op.drop_index(op.f('ix_busket_id'), table_name='busket')
    op.drop_index(op.f('ix_busket_pizza_id'), table_name='busket')
    op.drop_index(op.f('ix_busket_user_email'), table_name='busket')
    op.drop_table('busket')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('busket',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pizza_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pizza_value', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_email', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('busket_pkey'))
    )
    op.create_index(op.f('ix_busket_user_email'), 'busket', ['user_email'], unique=False)
    op.create_index(op.f('ix_busket_pizza_id'), 'busket', ['pizza_id'], unique=False)
    op.create_index(op.f('ix_busket_id'), 'busket', ['id'], unique=False)
    op.drop_index(op.f('ix_basket_user_email'), table_name='basket')
    op.drop_index(op.f('ix_basket_pizza_id'), table_name='basket')
    op.drop_index(op.f('ix_basket_id'), table_name='basket')
    op.drop_table('basket')
    # ### end Alembic commands ###
